export const actionTypes = {
  TICK: "TICK",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET"
};

export const accountTypes = {
  LOGIN: "LOGIN",
  VERIFIED: "VERIFIED"
};

export const journalTypes = {
  GET_ENTRIES: "GET_ENTRIES",
  SORT_ENTRIES: "SORT_ENTRIES",
  FILTER_ENTRIES: "FILTER_ENTRIES",
  TAGS: "TAGS",
  CREATE: "CREATE",
  DELETE: "DELETE",
  EDIT: "EDIT",
  SHOW_ENTRIES: "SHOW_ENTRIES",
  SHOW_FORM: "SHOW_FORM",
};

export const habitTypes = {
  SET_HABITS: "SET_HABITS",
  ADD_HABIT: "ADD_HABIT",
  EDIT_HABIT: "EDIT_HABIT",
  DELETE_HABIT: "DELETE_HABIT",
  SET_MODE: "SET_MODE",
  CURRENT_MONTH: "CURRENT_MONTH",
  INCREMENT_MONTH: "INCREMENT_MONTH",
  DECREMENT_MONTH: "DECREMENT_MONTH",
};